// Generated by CoffeeScript 1.7.1
var app, arg, configObj, koa, router, _i, _len, _ref;

koa = require('koa');

router = require('koa-router');

app = koa();

configObj = {
  root: __dirname,
  env: 'dev',
  port: 3000
};

_ref = process.argv;
for (_i = 0, _len = _ref.length; _i < _len; _i++) {
  arg = _ref[_i];
  if (arg === '--prod') {
    configObj.env = 'prod';
    configObj.port = 8080;
  }
}

require('./server/config')(app, configObj);

require('./server/db')(app, configObj);

app.use(function*(next) {
  var err;
  try {
    yield next;
  } catch (_error) {
    err = _error;
    console.log("error: " + err);
    this.app.emit('app.error', err, this);
    if (err.name === 'ValidationError') {
      return this.status = 400;
    }
    this.status = err.status || 500;
  }
});

app.on('app.error', function(err) {
  return console.error("app.error: " + err);
});

app.use(router(app));

require('./server/controllers/user')(app, configObj);

require('./server/controllers/matchday')(app, configObj);

app.listen(configObj.port);

console.log("listening on port " + configObj.port);
