// Generated by CoffeeScript 1.7.1
var ra;

ra = angular.module('ra');

ra.controller('NavBarController', [
  '$scope', '$state', '$modal', 'UserService', function($scope, $state, $modal, UserService) {
    $scope.addUser = function() {
      var modal;
      modal = $modal.open({
        templateUrl: '/tpls/user/new.html',
        controller: [
          '$scope', '$http', function($scope, $http) {
            $scope.user = {
              name: '',
              auth: {
                email: '',
                password: ''
              }
            };
            $scope.ok = function() {
              return $http.post('/users/add', $scope.user).success(function(data, status, headers, config) {
                var t;
                t = [data, status, headers, config];
                return modal.close('ok');
              }).error(function(data, status, headers, config) {
                var t;
                t = [data, status, headers, config];
                return modal.dismiss('error');
              });
            };
            return $scope.cancel = function() {
              return modal.dismiss('cancel');
            };
          }
        ],
        backdrop: 'static'
      });
      return modal.result.then(function() {
        return $state.transitionTo($state.current, {}, {
          reload: true,
          inherit: true,
          notify: true
        });
      }, function() {});
    };
    $scope.addMatchday = function() {
      var modal;
      modal = $modal.open({
        templateUrl: '/tpls/matchday/new.html',
        controller: [
          '$scope', '$http', function($scope, $http) {
            $scope.ok = function() {
              return $http.post('/matchdays/add', {}).success(function(data, status, headers, config) {
                var t;
                t = [data, status, headers, config];
                return modal.close('ok');
              }).error(function(data, status, headers, config) {
                var t;
                t = [data, status, headers, config];
                return modal.dismiss('error');
              });
            };
            return $scope.cancel = function() {
              return modal.dismiss('cancel');
            };
          }
        ],
        backdrop: 'static'
      });
      return modal.result.then(function() {
        return $state.transitionTo($state.current, {}, {
          reload: true,
          inherit: true,
          notify: true
        });
      }, function() {});
    };
    $scope.viewMatches = function(edit) {
      var manage;
      manage = edit ? 'manage' : null;
      return $state.go('matches', {
        manage: manage
      });
    };
    $scope.viewLast12 = function() {
      return $state.go('last12');
    };
    return $scope.signin = function() {
      var modal;
      modal = $modal.open({
        templateUrl: '/tpls/user/signin.html',
        controller: [
          '$scope', '$http', function($scope, $http) {
            $scope.user = {
              auth: {
                email: '',
                password: ''
              }
            };
            $scope.ok = function() {
              return $http.post('/users/signin', $scope.user).success(function(data, status, headers, config) {
                var t;
                t = [data, status, headers, config];
                UserService.signin(data);
                return modal.close('ok');
              }).error(function(data, status, headers, config) {
                var t;
                t = [data, status, headers, config];
                UserService.signout();
                return modal.dismiss('error');
              });
            };
            return $scope.cancel = function() {
              return modal.dismiss('cancel');
            };
          }
        ],
        backdrop: 'static'
      });
      return modal.result.then(function() {
        return $state.transitionTo('last12', {}, {
          reload: true,
          inherit: true,
          notify: true
        });
      }, function() {});
    };
  }
]);
