// Generated by CoffeeScript 1.7.1
var ra;

ra = angular.module('ra', ['ui.bootstrap', 'ui.router']);

ra.config([
  "$stateProvider", "$urlRouterProvider", function($stateProvider, $urlRouterProvider) {
    var shiftTemplate;
    shiftTemplate = "<div class='container'><div class='jumbotron text-center'><p>Loading...</p></div></div>";
    $urlRouterProvider.otherwise("/");
    return $stateProvider.state('index', {
      url: '/',
      views: {
        'main': {
          template: shiftTemplate,
          controller: [
            '$state', '$window', function($state, $window) {
              return $window.setTimeout(function() {
                return $state.go('matches');
              }, 0);
            }
          ]
        }
      }
    }).state("matches", {
      url: "/matches",
      resolve: {
        users: [
          '$http', function($http) {
            return $http.get('/users');
          }
        ],
        matchdays: [
          '$http', function($http) {
            return $http.get('/matchdays').then(function(data) {
              var d, matchdays, _i, _len, _ref;
              matchdays = {};
              _ref = data.data;
              for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                d = _ref[_i];
                matchdays[d.player] = d.score;
              }
              return matchdays;
            });
          }
        ]
      },
      views: {
        'main': {
          templateUrl: '/tpls/match/list.html',
          controller: [
            '$rootScope', '$state', 'users', 'matchdays', function($rootScope, $state, users, matchdays) {
              var user, _i, _len;
              for (_i = 0, _len = users.length; _i < _len; _i++) {
                user = users[_i];
                user.matchdays = matchdays;
              }
              $rootScope.capsule = {
                users: users,
                matchdays: matchdays
              };
            }
          ]
        }
      },
      auth: true
    });
  }
]);

ra.run([
  '$location', function($location) {
    var a;
    return a = $location;
  }
]);
