// Generated by CoffeeScript 1.7.1
var ra;

ra = angular.module('ra');

ra.factory('UserService', [
  '$http', function($http) {
    var sdo;
    return sdo = {
      id: null,
      name: '',
      reload: function() {}
    };
  }
]);
