// Generated by CoffeeScript 1.7.1
var exports, serve, session;

serve = require('koa-static');

session = require('koa-session');

exports = module.exports = function(app, config) {
  app.use(serve("" + config.root + "/client"));
  app.keys = ['8 oclock every friday'];
  return app.use(session());
};
