// Generated by CoffeeScript 1.7.1
var MatchDaySchema, mongoose;

mongoose = require('mongoose');

MatchDaySchema = new mongoose.Schema({
  id: Number,
  played_at: Date,
  scores: [
    {
      player: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User'
      },
      score: Number
    }
  ]
});
