// Generated by CoffeeScript 1.7.1
var User, arg, configObj, dbOptions, dbURI, fs, mongoose, path, thunkify, _i, _len, _ref;

fs = require('fs');

path = require('path');

mongoose = require('mongoose');

thunkify = require('thunkify');

configObj = {
  root: path.join(__dirname, '..'),
  env: 'dev',
  port: 3000
};

dbURI = {
  dev: 'mongodb://localhost/ra_dev',
  prod: 'mongodb://localhost/ra_prod'
};

User = require("" + configObj.root + "/server/models/user");

_ref = process.argv;
for (_i = 0, _len = _ref.length; _i < _len; _i++) {
  arg = _ref[_i];
  if (arg === '--prod') {
    configObj.env = 'prod';
    configObj.port = 8080;
  }
}

dbOptions = {
  server: {
    socketOptions: {
      keepAlive: 1
    }
  }
};

mongoose.connect(dbURI[configObj.env], dbOptions);

mongoose.connection.on('connected', function() {
  var herrlich;
  herrlich = new User({
    name: '克立',
    auth: {
      email: 'herrlich@qq.com',
      role: 'optr'
    }
  });
  herrlich.auth.password = '123456';
  debugger;
  return herrlich.save(function(error) {
    debugger;
    return process.exit(0);
  });
});
