// Generated by CoffeeScript 1.7.1
var User, models_path, mongoose, parse, thunkify, util;

mongoose = require('mongoose');

thunkify = require('thunkify');

parse = require('co-body');

util = require('util');

models_path = "" + __dirname + "/../models";

User = require("" + models_path + "/user");

exports.authenticate_action = function*(next) {
  console.log('check user');
  this.user = yield User.findOne({
    _id: this.session.current_user_id
  }).exec();
  if (this.user) {
    yield next;
  } else {
    this.status = 401;
  }
};

exports.authorize_action = function*(next) {
  var _ref;
  console.log('check user authorization');
  if (((_ref = this.user.auth.role) != null ? _ref.indexOf('optr') : void 0) !== -1) {
    yield next;
  } else {
    this.status = 401;
  }
};
